---
- name: first playbook
  hosts: all
  become: true
  tasks:
  
  - name: update ubuntu
    tags: always
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

  - name: update centos
    tags: always
    package:
      name: "*"
      state: latest
    when: ansible_distribution == "CentOS"
      

  - name: install apache for both servers
    tags: apache2, httpd
    package:
      name: "{{ apache_package }}"
      state: latest

  - name: copy default html site
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root

  - name: change admin e-mail on centos
    tags: admin, email
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAmind admin@gmail.com
    when: ansible_distribution == "CentOS"    
    register: email

  - name: restart centos
    tags: admin, email
    service:
      name: httpd
      state: restarted
    when: email.changed
